### ISSUE TITLE
[Beta 1.0.3] After creating second calendar set of notes I no longer can open open daily note

### ISSUE THREAD

**Issue by danieltomasz** [liamcain/obsidian-periodic-notes#104]
I created new set of notes, with daily notes enabled.
My previous note set was still my default. Since that moment I no longer  can oopen daily note, even after I removed the newly selected calendar set; I check the paths and they seem ok, I still can open  weekly notes from this calendar set

Obsidian 0.14.6, Periodic Notes 1.0.3beta

Edit: After reinstalling everything works ok, even the second calendar set creation
BTW I installed it via Brat,  the data file inside plugin folder  shows me "1.0.0-beta1" while in obsidian community menu I see ""1.0.0-beta3"

**Comment by liamcain** [comment]
Hi, I think you did uncover a bug. The plugin was not properly unloading, so when you upgraded, it didn't apply the new version until after the restart. I created a separate ticket just now to make sure that gets fixed in the next version:https://github.com/liamcain/obsidian-periodic-notes/issues/105
