### ISSUE TITLE
Week Number - customize / ISO 8601

### ISSUE THREAD

**Issue by b1uegh0st** [liamcain/obsidian-periodic-notes#13]
Hi, 
 
 Thanks for the plugin. 

 My issue is: I want this week (feb 22nd 2020 - feb 28th 2020) to count as week 08 of 2021. This is base on the ISO 8601 standard. Couldn't find anyway to change this from default (counted as W09) in Obsidian / this plugin / your calendar plugin.

 Changing the locale in Windows only change the week start date. 

 Can you help / upgrade the plugin.
 
 Ref:
 https://www.epochconverter.com/weeks/2021
![image](https://user-images.githubusercontent.com/6695697/108616248-64086c00-743e-11eb-9ff6-850aaf18a8d4.png)

**Comment by hepabolu** [comment]
If you check: https://momentjs.com/docs/#/parsing/string-format/

for the formatting, then you can easily fix this yourself by adding the `GGGG-[W]WW` format for the note.

What remains is the wrong weeknumber in the Calendar plugin

**Comment by liamcain** [comment]
Hi @b1uegh0st, there's currently no way to override the locale via Periodic Notes alone. However, if you have the calendar plugin installed, there is a confirmation option in the calendar settings. Go to `Settings > Calendar Settings > Override Locale`.

![image](https://user-images.githubusercontent.com/693981/107323054-a069be80-6a73-11eb-9a08-1730eee2be0c.png)

You can change this dropdown to a locale that abides by the ISO 8601 standard, e.g. `en-gb`.

You might need to restart Obsidian for this change to take effect.

---

Note, since you mentioned you have the Calendar plugin installed, I do **not** recommend you do as @hepabolu mentions since the plugins will become out of sync.

**Comment by b1uegh0st** [comment]
Hi @liamcain , thank you. I did try to change the locale in Windows (doesn't work / sync to obsidian somehow). But changing the setting in the calendar plugin does work (no-brainer, should have thought about it earlier).

Thanks.
