### ISSUE TITLE
Issue parsing weekly note title

### ISSUE THREAD

**Issue by np-22** [liamcain/obsidian-periodic-notes#14]
Hi, thanks for this great functionality! It worked great until recently I discovered my weekly note cannot be recognized. After some testing, I think this might relate to how I name the files. I am using `gggg-[W]ww_MM-DD`. If I switch to `gggg-[W]ww`, it works as expected.

**Comment by Johnson1602** [comment]
Same here, `gggg-[W]ww` works fine but my custom title format `gggg-MM-DD_[W]ww` cannot be parsed correctly. `2020-06-08_W24` shows up in `2021-03-08_W11` so that I can't create a weekly note for that week.

Also, I tried to create weekly notes for weeks after March, the files can be created but won't show up in the corresponding week numbers (also shows no dots). So I can't click the week number to open that week's note.

Using: macOS Big Sur 11.2.2 & Obsidian 0.11.3

Thanks for the work! Really appreciated.

**Comment by liamcain** [comment]
Sorry for the late reply, I can reproduce the issue. The date parser that I'm using seems to be getting confused by the `_` character. I will try to make a fix soon!

**Comment by np-22** [comment]
Thank you @liamcain!

**Comment by liamcain** [comment]
I made some improvements to how dates are parsed in the new version (0.0.10). Since the library I use to parse dates (`momentjs`) doesn't like mixing `DD`, `MM`, and `ww`, I added some custom logic that will help it resolve the datestring. I can't guarantee it works in all cases but `gggg-[W]ww_MM-DD` should be working now. 

Let me know if you run into any issues!

**Comment by np-22** [comment]
Awesome! Thanks @liamcain! After testing all weekly notes for 2021 work well for me. However when I checked notes from 2020, they cannot be recognized. For example, I can create `2020-W53_12-28` but after reloading the app it cannot be recognized again. I am using locale `en-gb`.

**Comment by liamcain** [comment]
Okay, I just published a new version of the calendar to hopefully resolve this. Let me know if you're still having issues @np-22

**Comment by np-22** [comment]
Hey @liamcain! Thanks for the fix! I cannot find new version of calendar from Obsidian but after manually putting the new version into plugin folder, I can confirm the issue has been fixed.

**Comment by liamcain** [comment]
> I cannot find new version of calendar from Obsidian

Whoops! thanks for the heads up, I forgot to make the new version available in obsidian. Should be good now. Thanks for testing the long way! 🙏

**Comment by Johnson1602** [comment]
> > I cannot find new version of calendar from Obsidian
> 
> Whoops! thanks for the heads up, I forgot to make the new version available in obsidian. Should be good now. Thanks for testing the long way! 🙏

It works perfectly now! Thanks so much!
