### ISSUE TITLE
Different daily note templates for different days of the week

### ISSUE THREAD

**Issue by jacklaing** [liamcain/obsidian-periodic-notes#15]
I know this isn't exactly what you intended this plugin to be for, but I wonder if the backend functionality could be extended to allow us to create different daily note templates for different days of the week.

This would be extremely useful for people who tend to do the same things on certain weekdays or, probably the most common example, people who have different weekend schedules.

**Comment by haru-mamburu** [comment]
I also think it will be very useful.

**Comment by ChronicAdrift** [comment]
Should be possible using the solution discussed in #61.

**Comment by liamcain** [comment]
Since this is possible using Templater, I don't plan on including this in Periodic Notes. Templater is already more flexible than anything I can provide with this plugin.

Closing this for now, but I can dig around to see if there is a good template that I can showcase in the README for how to do this.
