### ISSUE TITLE
Weeknote opens wrong week (next week)

### ISSUE THREAD

**Issue by KingOfSpades** [liamcain/obsidian-periodic-notes#17]
Hey

When I'm using your (great) plug-in on macOS `11.2.2 (20D80)` with Obsidian `v0.11.5` and I use the 'Open Weekly Note' function it opens the note of W10. But it is W09 at the moment:

![Weekly note bug](https://user-images.githubusercontent.com/2156115/109933665-faa11c80-7ccb-11eb-9f2e-ae0c6554c02e.gif)

What might be causing this? I already had a note with the name `2021-W09` when I installed you plug-in. Could it be that the plug-in opens 'the last note created' instead of the current week number?

**Comment by KingOfSpades** [comment]
Just used the 'Open this week's note' command and it creates and opens the next weeks note (`2021-W11`)

**Comment by fishcymbal** [comment]
Just for context, I've had this issue with many different programs and code blocks and am getting the same result as @KingOfSpades, but it might not be a bug in @liamcain's code. It might be the way some computers or calendar programs are set to count the first week of the year. I think it has to do with how you count where January 1 falls. 

For example, in Fantastical on my Mac, it shows January 1 as Week 53 of 2020. So all my successive weeks are off by one. Not sure if it's a matter of operating system settings, or if it's Fantastical giving me the wrong week number. The built-in Mac app "Calendar" says January 1 falls on Week 1 of 2021. 

[This site](https://www.epochconverter.com/weeknumbers) ~~adds to the confusion~~ gives more information.

**Comment by liamcain** [comment]
Hi @KingOfSpades, you're not alone, this is the cause of a lot of confusion. By default, the Periodic Notes plugin uses the locale's Week number (rather than the ISO 8601 week number). In your settings, the weekly note format looks like this 
<img width="909" alt="image" src="https://user-images.githubusercontent.com/693981/110349727-fa24c080-8000-11eb-82b2-99677aa61dc6.png">

If you want to use the ISO 8601 international week numbering standard, you can do so by changing your weekly note format to `gggg-[W]WW`. The [`WW`](https://momentjs.com/docs/#/displaying/format/) here tells it to use ISO numbers instead.

---

### Note: If you use the Calendar plugin

If you use the Calendar plugin, you can alternatively change the locale that the Periodic Notes plugin is using. There are some instructions for how to do so here: https://github.com/liamcain/obsidian-periodic-notes/issues/13. This is the **recommended** fix since it keeps compatibility with other plugins. The fact that the settings aren't also in the Periodic Note plugin settings was an oversight on my part. I'll try to include them soon.

**Comment by KingOfSpades** [comment]
@liamcain thanks so much! This indeed fixes the 'issue'. I'll close this issue. Thanks again!
