### ISSUE TITLE
Differences between this plugin and Daily Notes

### ISSUE THREAD

**Issue by sagikazarmark** [liamcain/obsidian-periodic-notes#19]
Hey,

Thanks a lot for your work on Obsidian plugins!

I wonder what the differences are between the Daily notes and this plugin.  Is it just an extended version?

I'm also curious whether lynchjames/obsidian-day-planner#20 will work with this plugin (instead of Daily notes).

**Comment by liamcain** [comment]
This plugin is mainly just an extended version of the Daily Notes plugin (since it adds weekly and monthly notes). In the future, I might break compatibility with the daily notes plugin and add additional features, such as new template variables (#16) or better note navigation.

Unfortunately, the day planner author has been MIA for a while. I have considered forking the library myself to improve compatibility.

**Comment by sagikazarmark** [comment]
I think it would be great if this plugin preserved some sort of interoperability with the core Daily Notes plugin (I mean replace it, but provide the same interface).

It would make integrations with other plugins much more easier. The Review and the Slated plugins come to mind (in addition to the Day Planner).

**Comment by liamcain** [comment]
Totally agree! That's why this plugin is built on top of the [`daily-notes-interface`](https://github.com/liamcain/obsidian-daily-notes-interface) which is another package I wrote to provide the plugin interoperability. Slated and Review already use that package which is why they support this plugin OR the daily notes plugin.

**Comment by sagikazarmark** [comment]
That's great news! I guess the Day Planner just need to use that interface then.

Thanks again for the plugin.
