### ISSUE TITLE
Enabling Periodic Notes force Calendar plugin to Ignore Daily Notes Obsidian Plugin settings

### ISSUE THREAD

**Issue by danieltomasz** [liamcain/obsidian-periodic-notes#21]
Enabling Periodic Note force Calendar plugin to Ignore Daily Notes Obsidian Plugin settings, even if Daily Notes setting is disabled

see Here https://github.com/liamcain/obsidian-calendar-plugin/issues/148

**Comment by liamcain** [comment]
Hi @danieltomasz, sorry for the frustration! Just to confirm, you had the "Daily Notes" toggle disabled on Periodic Notes but the calendar was still trying to use those settings instead of the Daily Notes plugin?
 
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/693981/111054222-ea5e0f80-8438-11eb-987d-5160627421d3.png">

**Comment by danieltomasz** [comment]
When I have weekly and monthly notes enabled and daily notes disabled in the menu above calendar was ignoring Obsidian daily note setting and the daily note was created empty at root of the vault when clicking on new day in calendar view

**Comment by liamcain** [comment]
Okay, I understand now. Definitely not intentional; I'll have a fix for this in the next version. Thanks for the report!

**Comment by liamcain** [comment]
Okay, so I just published a new version of the Calendar (1.5.4) and Periodic Notes (0.0.10). This should now properly respect having `Daily Notes` toggled off in Periodic notes.

Sorry for the frustration this must have caused! Let me know if you run into any other issues.

**Comment by danieltomasz** [comment]
Thanks for making and the maintenance of  the plugins, my journal rely on it ;) I will update now!
