### ISSUE TITLE
possible weekly note bug

### ISSUE THREAD

**Issue by swuphoto** [liamcain/obsidian-periodic-notes#88]
I setup my weekly note's file name to a pattern "YYYY-MM-DD  [W]ww" inside Periodic Note Plugin, it works fine when creating new note by clicking on the week number on the calendar.

however, it failed to identify/link to the first week 2021-12-27 W01 once created, the calendar dot didn't appear, even the file existed after creation.  All following weeks are working as expected.

**Comment by liamcain** [comment]
The issue is that you should always use `GGGG` instead of `YYYY` for weekly note formats.

**GGGG** is the current _week year_.  On December 27th, the current year is 2021. However, the current week year is actually 2022, since this is the first week of 2022. **GGGG** and **YYYY** will return the same values for almost every day of the year. However, it's important for cases like this, where a week falls between 2 years.
