### ISSUE TITLE
1.0 beta - search???

### ISSUE THREAD

**Issue by pcause** [liamcain/obsidian-periodic-notes#99]
The video has search finding things with natural language dates  I have that installed but how did you get the search invoked.  perhaps because I am using "Another Quick Switcher"??  I'll try to disable that and go back to core.  You might want to put a note somewhere about this if that is the problem.

EDIT:  Figured it out.  had to use the periodic note sub-command.  But I entered "1 week from today" with a day note open.  Only showed a weekly note and today's note as choice. today is 2022-04-11  so so would have expected an option for 2022-04-18 and an indication that it didn't exist (enter to create)

**Comment by liamcain** [comment]
The natural language parsing doesn't handle all cases perfectly, so this is an instance where it can't interpret `"1 week from today"`. I am going to transfer this issue to the NLDates plugin repo since that's what's powering the search currently.

Here's a link to the issue if you want to track it: https://github.com/argenos/nldates-obsidian/issues/95
